### ISSUE TITLE
is:issue is:open 请问您加入non-local模块的时候，也有出现过加入non-local反倒准确度下降的问题吗

### ISSUE THREAD

**Issue by firghting** [AsuradaYuci/awesome_video_person_reid#2]
is:issue is:open 请问您加入non-local模块的时候，也有出现过加入non-local反倒准确度下降的问题吗

**Comment by AsuradaYuci** [comment]
反正没有像很多论文说的那样，直接加入non-local模块会有性能的提升。可能怎么插入，在哪几层插入都有讲究。

**Comment by AsuradaYuci** [comment]
@firghting
