### ISSUE TITLE
Enviroment related to MARS dataset

### ISSUE THREAD

**Issue by hppy152** [AsuradaYuci/awesome_video_person_reid#3]
Would you like to share the environment in which you run the program for the MARS dataset? Such as GPU, RAM and pytorch version.

Would you like to help me?

**Comment by AsuradaYuci** [comment]
Atleast two 1080Ti/2080TI GPUs, 32G/64G RAM, pytorch version >= 1.0.

**Comment by hppy152** [comment]
Ok, I got it. Thank you for your reply
